### Register API Test
POST http://20.244.56.144/evaluation-service/register
Content-Type: application/json

{
  "email": "saireddy.annamareddy@gmail.com",
  "name": "Annamareddy Jyothi Saireddy",
  "mobileNo": "9182284144",
  "githubUsername": "SaiReddyA-1",
  "rollNo": "23P35A4402",
  "accessCode": "NFwgRT"
}

POST http://20.244.56.144/evaluation-service/auth
Content-Type: application/json

{
  "email": "ramkrishna@abc.edu",
  "name": "ram krishna",
  "rollNo": "aalbb",
  "accessCode": "xgAsNC",
  "clientID": "d9cbb699-6a27-44a5-8d59-8b1befa816da",
  "clientSecret": "tVJaaaRBSeXcRXEM"
}






# HTTP/1.1 200 OK
# date: Thu, 26 Jun 2025 07:10:35 GMT
# content-type: application/json; charset=utf-8
# content-length: 207
# connection: close
# access-control-allow-credentials: true
# access-control-allow-headers: Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization, accept, origin, Cache-Control, X-Requested-With
# access-control-allow-methods: POST, OPTIONS, GET, PUT
# access-control-allow-origin: *
# trace-id: d2751a97-c53d-40e3-bc48-ad748ae6ff7d
# x-content-type-options: nosniff
# x-xss-protection: 1;mode=block

# {
#   "email": "saireddy.annamareddy@gmail.com",
#   "name": "annamareddy jyothi saireddy",
#   "rollNo": "23p35a4402",
#   "accessCode": "NFwgRT",
#   "clientID": "6705030e-3879-40f5-88f3-bd2c97198d86",
#   "clientSecret": "uYHVKnPBTgvARqqX"
# }